### ISSUE TITLE
uninstalling KDX 

### ISSUE THREAD

**Issue by demisrael** [aspectron/kdx#6]
I am uninstalling KDX and removing "Data Folder" but then, after installing KDX again, it is not asking for "Recover Wallet" but for Wallet encryption key. Can I totally remove all KDX components so it will forget my Wallet?

**Comment by aspect** [comment]
KDX uses 2 separate folders for data storage and wallet storage.

KDX data storage is managed by KDX and contains process data (usually located in `<home>/.kdx`

The wallet storage, however, is located in a standard bitcoin-like location which on windows is `C:\Users\<username>\AppData\Local\Kaspa`  (in which you can find `*.kpk` files)

The wallet is managed by the kaspa wallet framework which is the same framework used in PWA, KDX as well as CLI.  This means that you can install and run CLI and KDX and they will detect and manage the same wallet.

We will be updating documentation in the coming weeks and will add this information to it.

**Comment by aspect** [comment]
Oh, I think there is a misunderstanding - I am referring to our CLI wallet that is built on top of the same wallet framework as KDX and PWA.  Our CLI uses same folders and 'kpk' wallet files as KDX.  You need latest nodejs and you can install it with `npm install -g @kaspa/wallet-cli`  and then run `kaspa-wallet`.  This CLI provides you with all the functionality needed to interact with the wallet, `kaspa-wallet balance` will show your wallet balance etc. Run `kaspa-wallet help` to get a full list of commands.

This is not related to the native CLI wallet developed as a part of Kaspa, which last time I checked was not an HD-capable wallet (it allow the creation and sending to addresses but does not maintain seed or an address list etc.).

**Comment by demisrael** [comment]
hi! 
followed your instructions, i did run npm install on my machine where nodejs never seen in past and got following error (dependencys?)

$ kaspa-wallet help
/usr/lib/node_modules/@kaspa/wallet-cli/kaspa-wallet.js:48
			errorCB?.(count)
			        ^

SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by mbunal** [comment]
> The wallet storage, however, is located in a standard bitcoin-like location which on windows is `C:\Users\<username>\AppData\Local\Kaspa` (in which you can find `*.kpk` files)

what is this locaion on macos?

**Comment by surinder83singh** [comment]
on MacOS wallet storage location is:    `/Users/<username>/Library/Application Support/Kaspa/`

**Comment by mbunal** [comment]
> on MacOS wallet storage location is: `/Users/<username>/Library/Application Support/Kaspa/`

thank you....
